### ISSUE TITLE
Reorder Page Not Loading

### ISSUE THREAD

**Issue by NetTech2001** [netbox-community/netbox-reorder-rack#12]
### netbox-reorder-rack version

4.0.2

### Python version

3.11

### Steps to Reproduce

Click re-order button

### Expected Behavior

you should be presented with a page to click and drag devices to a new location in the rack.

### Observed Behavior

Page load with no devices.

![image](https://github.com/netbox-community/netbox-reorder-rack/assets/128771411/58a1a863-74f3-47f1-ba05-1093819f4b80)

**Comment by minitriga** [comment]
Hello @NetTech2001 can you try to recollect static using the following commands:

```
python3 manage.py collectstatic --no-input
systemctl restart netbox
```

**Comment by NetTech2001** [comment]
works until I restart the Netbox docker container, any idea how would one make this persistent inside Docker?


Keith Knowles

Lethbridge College

Senior Network Analyst, ITS
Ph. 403-320-3202 #5811
3000 College Drive S., Lethbridge, AB T1K 1L6



*Reach me on Microsoft ***@***.***> for chat, video or voice calls. Contact the help ***@***.***> if you need help.



________________________________

**Comment by NetTech2001** [comment]
Solved by adding

COPY ./configuration/load_plugin.py /etc/netbox/config/load_plugin.py
RUN SECRET_KEY="_read_secret('secret_key', environ.get('SECRET_KEY', ''))" /opt/netbox/venv/bin/python3 manage.py collectstatic --no-input

to the Dockerfile-Plugins

and creating file configuration/load_plugin.py thats contains only

PLUGINS = ['netbox_reorder_rack']

Then issue a docker compose build --no-cache to properly build the latest release.





Keith Knowles

Lethbridge College

Senior Network Analyst, ITS
Ph. 403-320-3202 #5811
3000 College Drive S., Lethbridge, AB T1K 1L6



*Reach me on Microsoft ***@***.***> for chat, video or voice calls. Contact the help ***@***.***> if you need help.



________________________________

**Comment by minitriga** [comment]
Perfect yes this is the best way to do it :) 

https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins#dockerfile-plugins

Thank you I will close the issue. Let me know if you have further issues.
