### ISSUE TITLE
Excessive change log entries

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox-reorder-rack#16]
### netbox-reorder-rack version

v0.2.0

### Feature type

Change to existing functionality

### Proposed functionality

When moving a device to a new position, it should not make any changes to other devices in the rack.

### Use case

When moving a device to a new position, this plugin creates 2 change log entries for every device in the rack.  First to set its position to null, and then to set it back to its original position.  This makes it difficult to use the change log in a meaningful way.

**Comment by cruse1977** [comment]
Occurs in [this code](https://github.com/netbox-community/netbox-reorder-rack/blob/main/netbox_reorder_rack/api/views.py) in SaveViewset()

`            serializer = ReorderRackSerializer(request.data)
            with transaction.atomic():
                for device in rack.devices.all():
                    device.position = None
                    device.clean()
                    device.save()

                for new in request.data["front"]:
                    device = rack.devices.filter(pk=new["id"]).first()
                    device.position = decimal.Decimal(new["y"])
                    device.face = new["face"]
                    device.clean()
                    device.save()

                for new in request.data["rear"]:
                    device = rack.devices.filter(pk=new["id"]).first()
                    device.position = decimal.Decimal(new["y"])
                    device.face = new["face"]
                    device.clean()
                    device.save()

                return Response(
                    {"message": "POST request received", "data": serializer.data},
                    status=status.HTTP_201_CREATED,
                )`

The question is why, vs comparing for a changed location or face and only saving those objects.
