### ISSUE TITLE
Display device type image

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox-reorder-rack#18]
### netbox-reorder-rack version

v1.1.0

### Feature type

Data model extension

### Proposed functionality

Display the front/rear picture of the device type for each device like in the normal rack view

### Use case

Better clarity when viewing the rack

**Comment by minitriga** [comment]
I have added the ability to load device type images. Due to how things are loaded and how the Javascript work currently if you move a device from front to back etc it may loose the images. Will need to have a proper think about how to fix that in future.
