### ISSUE TITLE
Unracked devices are labeled "None"

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox-reorder-rack#21]
### netbox-reorder-rack version

v1.1.1

### Python version

3.12

### Steps to Reproduce

1. Create a new rack
2. Add 1 or more devices to the rack without a position
3. Click reorder rack

### Expected Behavior

It should show the same label as the /dcim/racks/xxx page and respect the labels vs images preference.

### Observed Behavior

All the unracked devices are labeled "None" so it's impossible to identify them
<img width="1123" alt="image" src="https://github.com/netbox-community/netbox-reorder-rack/assets/3991046/fa104d96-c2fb-43c0-b633-92d203c7c2af">

**Comment by llamafilm** [comment]
After further review, it looks like this issue only happens when the device is unnamed.

**Comment by cruse1977** [comment]
Possible requirement for ability to cope with empty device names, however what field could be used as an identifier - ID is obvious but does not help usability; description would be potentially be too long.

**Comment by Azmodeszer** [comment]
NetBox normally shows the Device Type for unnamed devices in the rack elevation view.

**Comment by llamafilm** [comment]
Oops, yes that’s what I meant.
