### ISSUE TITLE
Unable to Save rack changes

### ISSUE THREAD

**Issue by BartZimmo** [netbox-community/netbox-reorder-rack#23]
### netbox-reorder-rack version

v1.1.1

### Python version

3.12

### Steps to Reproduce

Click on the Reorder button on a rack page.

At the start, the SAVE button is greyed out as expected
After you changed the position of a device, the SAVE button lights up.
Press the SAVE button.

Running Netbox 4.0.8

### Expected Behavior

After pressing the SAVE button, changes should be processed, and you can leave the page without issues.

### Observed Behavior

You can press it multiple times, but nothing happens.
If you reload or change to another tab, you will receive the following message:

This page is asking you to confirm that you want to leave — information you’ve entered may not be saved.

**Comment by minitriga** [comment]
Hello currently away on holiday but will look to get this looked at in two weeks or so.

Could you add any logs if there are any in the netbox logs.

**Comment by cruse1977** [comment]
hi @BartZimmo  can you give more details on your os/browser setup please ? using Netbox 4.0.10 and latest chrome I've been unable to replicate this.

**Comment by Hypercookie** [comment]
At least in my case this occurs because I have devices with device bays in this rack ( and devices which are contained in these bays). On pressing save I get a 500 Response because "Child devices can not be assigned a rack face".

**Comment by BartZimmo** [comment]
Hi,
Sorry for the late reply.
I was on vacation for 2 weeks.
I tried replicatin the issue this moring and suddenly, it all works like a charme.
Even with Devices that thave bays.
Tested with MS edge and Firefox.

**Comment by minitriga** [comment]
We will be releasing a new release soon once out it would be good to see if this is still present. We also add notifications on the front end for errors so this may help diagnose.

**Comment by BartZimmo** [comment]
Super!
I will update the plugin once it is released.

**Comment by minitriga** [comment]
New release is out.

**Comment by minitriga** [comment]
Closing issue. Reopen if there are still issues
